all:
	gcc									\
		-I Includes						\
		Sources/main.c					\
		Sources/callbacks.c				\
		Sources/camera.c				\
		Sources/model.c					\
		Sources/draw.c					\
		Sources/game.c					\
		Sources/texture.c				\
		Sources/light.c					\
		Sources/helpmenu.c				\
		-std=c11						\
		-lSOIL							\
		-lglut32						\
		-lopengl32						\
		-lglu32							\
		-lm								\
		-o Game.exe
		-lobj
